apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typegate.fullname" . }}
  labels:
    {{- include "typegate.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
  {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "typegate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "typegate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "typegate.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_URL
              value: redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:{{ .Subcharts.redis.Values.master.service.ports.redis }}/0
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redis.secretName" .Subcharts.redis }}
                  key: {{ template "redis.secretPasswordKey" .Subcharts.redis }}
            - name: TG_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "typegate.fullname" .) .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.secretKey }}
            - name: TG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "typegate.fullname" .) .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.adminPasswordKey }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 7890
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
