{{- if eq .Values.auth.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typegate.fullname" . }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKey }}: {{ .Values.auth.secret | b64enc | quote }}
  {{ .Values.auth.secretKeys.adminPasswordKey }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}