{{- if eq .Values.auth.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typegate.fullname" . }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.adminPassword }}: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{ .Values.auth.secretKeys.secret }}: {{ .Values.auth.secret | b64enc | quote }}
  {{ .Values.s3.secretKeys.accessKeyId }}: {{ .Values.s3.accessKeyId | b64enc | quote }}
  {{ .Values.s3.secretKeys.secretAccessKey }}: {{ .Values.s3.secretAccessKey | b64enc | quote }}
{{- end }}