apiVersion: v2
name: typegate
description: A Helm chart for Typegate
type: application
version: 0.2.0
appVersion: "0.1.7"
icon: https://metatype.dev/images/logo.svg
dependencies:
  - name: redis
    condition: redis.enabled
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
