apiVersion: v2
name: typegate
description: A Helm chart for Typegate
type: application
version: 0.1.1
appVersion: "0.1.7"
dependencies:
  - name: redis
    condition: redis.enabled
    version: "17.10.x"
    repository: "https://charts.bitnami.com/bitnami"
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
