on:
  push:
    branches:
      - main

jobs:
  test-pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
      - uses: helm/chart-releaser-action@v1.5.0
        env:
          charts_repo_url: https://charts.metatype.dev
          skip_existing: true
          mark_as_latest: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
