on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3
      - name: Add helm repo for dependencies
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mkdir -p public
          mv README.md public/index.md
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: charts.metatype.dev
          enable_jekyll: true
      - uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_SKIP_EXISTING: true
          CR_OWNER: metatypedev
          CR_GIT_REPO: charts
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
