on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4
      - name: Add helm repo for dependencies
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Lint charts
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency build $dir
            helm lint $dir --strict
          done
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_OWNER: metatypedev
          CR_GIT_REPO: charts
          CR_SKIP_EXISTING: true
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
